name: mobile_hris
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "assets/HR_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/