name: mobile_hris
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  dio: ^4.0.6
  geocoding: ^2.0.5
  intl: ^0.18.0
  geolocator: ^9.0.1
  flutter_svg: ^2.0.7
  get_storage: ^2.1.1
  image_picker: ^0.8.6
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "assets/HR_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/